### ISSUE TITLE
In Example, must be: MESSAGE(CustomerList.Name.Value);

### ISSUE THREAD

**Issue by d365nav** [MicrosoftDocs/navdevitpro-content-pr#2010] opened 2019-11-20 11:35 UTC
In Example, must be: MESSAGE(CustomerList.Name.Value);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83281880-9179-0bdf-0ce1-bc80ece7b7f0
* Version Independent ID: f143b15b-a9c3-f82f-c066-c9b53ff99f89
* Content: [PREVIOUS Function (TestPage) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/previous-function--testpage-)
* Content Source: [dynamics-nav/PREVIOUS-Function--TestPage-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/PREVIOUS-Function--TestPage-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment] 2019-11-22 10:20
Closing duplicate of #2011

**Closed by SusanneWindfeldPedersen** 2019-11-22 10:20 UTC
