### ISSUE TITLE
NAV 2018 CU2 missing?

### ISSUE THREAD

**Issue by ZepposBE** [MicrosoftDocs/navdevitpro-content-pr#2063] opened 2020-03-04 08:27 UTC
1.Upgrade to Microsoft Dynamics NAV 2018 Cumulative Update 2:
a.Download Microsoft Dynamics NAV 2018 CU2. --&gt; Results in Error, try again later.

I need to upgrade a NAV2013R2 to BC14 so I wanted to follow these steps. Any idea when/if the CU2 will be avaiable again?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ad68b4-a86e-c466-a4e4-02b782797b1a
* Version Independent ID: c9c43a69-4dd6-7d51-abf0-4c4312904966
* Content: [Upgrading to Microsoft Dynamics NAV 2018 - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/upgrading-to-microsoft-dynamics-nav)
* Content Source: [dynamics-nav/Upgrading-to-Microsoft-Dynamics-NAV.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Upgrading-to-Microsoft-Dynamics-NAV.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by sweikelt** [comment] 2020-05-28 08:27
@ZepposBE 

https://www.microsoft.com/en-us/download/details.aspx?id=56517

**Comment by edupont04** [comment] 2020-05-28 08:41
Closing this since the problem was caused by a temporary issue on the download page.

**Closed by edupont04** 2020-05-28 08:41 UTC
Labels: invalid

**Comment by sweikelt** [comment] 2020-05-28 08:51
@edupont04 
sorry, but did you click the link?
it's refering to
https://support.microsoft.com/de-de/help/4078580/cumulative-update-02-for-microsoft-dynamics-nav-2018-build-20348?preview
which says - An Error occured

if you use 
https://support.microsoft.com/de-de/help/4078580/cumulative-update-02-for-microsoft-dynamics-nav-2018-build-20348

(without the "?preview")
it works
